### ISSUE TITLE
Hoja excell - datos a pasar

### ISSUE THREAD

**Issue by anacid** [anacid/Maderas-Lusaja#1]
Según la hoja excell,

**Comment by anacid** [comment]
![image](https://zube.io/files/anacid/f4c571be2f6002c58ed6c75277c6d148.png)

La columna EMPCLI, es si la empresa es de Lusaja, o de comercila
La columna VEHCLI, detalle del vehículo para envío de la mercancía, si es de Lusaja o si es de una agencia de transporte.
La columna MATCLI, la matrícula del vehículo.

Estos datos si tenemos que pasarlos.

**Comment by anacid** [comment]
![image](https://zube.io/files/anacid/455f45333a1e031200e078f08b5542d3.png)

La Columna de PAGOS, se refiere a la forma de pago de los clientes, y según Rosi, no es necesario que la pasemos, porque los va a poner ella a mano, puesto que antes, la única forma que ponía era REPOSICION, para todos la misma,

**Comment by gregorioruiz** [comment]
MATCLIE y VEHCLIE se pasan como texto. Crear los datos.

EMPCLIE lo vamos a traspasar como comercial
Habrá que crear primero los comerciales para saber cual asignar a cada cliente.
